apiVersion: v1
kind: ConfigMap
metadata:
  name: cs-api-config
data:
  MODEL_PATH: "outputs/awq"
  FINETUNED_PATH: "outputs/dpo"
  FINETUNED_RATIO: "0.1"
  MAX_NEW_TOKENS: "512"
  TEMPERATURE: "0.7"
  TOP_P: "0.9"
  LOG_LEVEL: "INFO"