apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cs-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
    - host: cs-api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cs-api-service
                port:
                  number: 80