apiVersion: v1
kind: Service
metadata:
  name: cs-api-service
  labels:
    app: cs-api
spec:
  type: ClusterIP
  selector:
    app: cs-api
  ports:
    - name: http
      port: 80
      targetPort: 8000