apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cs-api-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: cs-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s